import { Bell, Check, CreditCard, Plus, RefreshCw, Save, Trash2, WalletCards, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { DataTable } from "../components/DataTable";
import { Badge, Button, Card, EmptyState, ErrorState, Input, PageHeader, Select, Textarea } from "../components/ui/primitives";
import { useApiResource } from "../hooks/useApiResource";
import { api } from "../services/api";

const money = (amount, currency = "INR") => new Intl.NumberFormat("en-IN", { style: "currency", currency, maximumFractionDigits: 2 }).format(Number(amount || 0));
const date = (value) => value ? new Date(value).toLocaleDateString("en-IN") : "-";
const tone = (status) => ({ PAID: "success", SUCCESS: "success", PENDING: "warning", PROCESSING: "accent", OVERDUE: "danger", FAILED: "danger", ERROR: "danger", CANCELLED: "neutral", DRAFT: "neutral", WARNING: "warning", INFO: "accent" }[status] || "neutral");

function Modal({ title, children, onClose, busy }) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-3" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) onClose(); }}><section className="max-h-[90vh] w-full max-w-xl overflow-hidden rounded-lg border border-line bg-white shadow-xl"><header className="flex items-center justify-between border-b border-line px-5 py-4"><h2 className="font-semibold">{title}</h2><button className="rounded-md p-2 hover:bg-slate-100" type="button" onClick={onClose} disabled={busy} aria-label="Close"><X size={18} /></button></header><div className="overflow-y-auto p-5">{children}</div></section></div>;
}

function Summary({ label, value }) {
  return <Card bodyClassName="p-4"><p className="text-xs font-medium text-muted">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></Card>;
}

export function BillingPage() {
  const invoices = useApiResource("/api/billing", []);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ clientName: "", amount: "", currency: "INR", dueDate: "", status: "PENDING", notes: "" });
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const filtered = useMemo(() => invoices.data.filter((row) => (!status || row.status === status) && (!query || `${row.invoiceNumber} ${row.clientName}`.toLowerCase().includes(query.toLowerCase()))), [invoices.data, query, status]);
  const totals = invoices.data.reduce((sum, row) => ({ billed: sum.billed + row.amount, paid: sum.paid + (row.status === "PAID" ? row.amount : 0), pending: sum.pending + (["PENDING", "OVERDUE"].includes(row.status) ? row.amount : 0) }), { billed: 0, paid: 0, pending: 0 });
  async function create(event) { event.preventDefault(); setBusy(true); setError(""); try { await api("/api/billing", { method: "POST", body: JSON.stringify(form) }); setShowForm(false); setForm({ clientName: "", amount: "", currency: "INR", dueDate: "", status: "PENDING", notes: "" }); await invoices.reload(); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  async function update(id, nextStatus) { try { await api(`/api/billing/${id}`, { method: "PATCH", body: JSON.stringify({ status: nextStatus }) }); await invoices.reload(); } catch (err) { setError(err.message); } }
  async function remove(id) { try { await api(`/api/billing/${id}`, { method: "DELETE" }); await invoices.reload(); } catch (err) { setError(err.message); } }
  return <div className="space-y-6"><PageHeader eyebrow="Finance" title="Billing" action={<div className="flex gap-2"><Button variant="secondary" onClick={invoices.reload}><RefreshCw size={16} />Refresh</Button><Button onClick={() => setShowForm(true)}><Plus size={16} />Invoice</Button></div>} />{(invoices.error || error) && <ErrorState message={invoices.error || error} onRetry={invoices.reload} />}<div className="grid gap-3 sm:grid-cols-3"><Summary label="Total billed" value={money(totals.billed)} /><Summary label="Paid" value={money(totals.paid)} /><Summary label="Outstanding" value={money(totals.pending)} /></div><Card title="Invoices"><div className="mb-4 grid gap-3 sm:grid-cols-[1fr_190px]"><Input placeholder="Search invoice or client" value={query} onChange={(e) => setQuery(e.target.value)} /><Select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option>{["DRAFT", "PENDING", "PAID", "OVERDUE", "CANCELLED"].map((item) => <option key={item}>{item}</option>)}</Select></div><DataTable loading={invoices.loading} rows={filtered} columns={[{ header: "Invoice", cell: (row) => <><p className="font-semibold">{row.invoiceNumber}</p><p className="text-xs text-muted">{row.clientName}</p></> }, { header: "Amount", cell: (row) => money(row.amount, row.currency) }, { header: "Due", cell: (row) => date(row.dueDate) }, { header: "Status", cell: (row) => <Select className="h-8 min-w-32" value={row.status} onChange={(e) => update(row.id, e.target.value)}>{["DRAFT", "PENDING", "PAID", "OVERDUE", "CANCELLED"].map((item) => <option key={item}>{item}</option>)}</Select> }, { header: "", sortable: false, cell: (row) => <Button className="h-8 !px-2" variant="danger" onClick={() => remove(row.id)} aria-label="Delete invoice"><Trash2 size={14} /></Button> }]} /></Card>{showForm && <Modal title="Create Invoice" busy={busy} onClose={() => setShowForm(false)}><form className="grid gap-3" onSubmit={create}><Input placeholder="Client name" required value={form.clientName} onChange={(e) => setForm({ ...form, clientName: e.target.value })} /><div className="grid grid-cols-[1fr_110px] gap-3"><Input type="number" min="0.01" step="0.01" placeholder="Amount" required value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /><Input maxLength={3} value={form.currency} onChange={(e) => setForm({ ...form, currency: e.target.value.toUpperCase() })} /></div><Input type="date" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} /><Textarea placeholder="Notes" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setShowForm(false)}>Cancel</Button><Button disabled={busy}>{busy ? "Saving..." : "Create"}</Button></div></form></Modal>}</div>;
}

export function VendorPaymentsPage() {
  const payments = useApiResource("/api/vendor-payments", []);
  const vendors = useApiResource("/api/vendors", []);
  const [filter, setFilter] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ vendorId: "", amount: "", currency: "INR", period: "", reference: "", status: "PENDING" });
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const rows = payments.data.filter((row) => !filter || (row.vendorId?.id ?? row.vendorId) === filter);
  async function create(event) { event.preventDefault(); setBusy(true); setError(""); try { await api("/api/vendor-payments", { method: "POST", body: JSON.stringify(form) }); setShowForm(false); await payments.reload(); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  async function update(id, status) { try { await api(`/api/vendor-payments/${id}`, { method: "PATCH", body: JSON.stringify({ status }) }); await payments.reload(); } catch (err) { setError(err.message); } }
  async function remove(id) { try { await api(`/api/vendor-payments/${id}`, { method: "DELETE" }); await payments.reload(); } catch (err) { setError(err.message); } }
  const paid = payments.data.filter((row) => row.status === "PAID").reduce((sum, row) => sum + row.amount, 0);
  return <div className="space-y-6"><PageHeader eyebrow="Finance" title="Vendor Payments" action={<Button onClick={() => setShowForm(true)}><Plus size={16} />Payment</Button>} />{(payments.error || vendors.error || error) && <ErrorState message={payments.error || vendors.error || error} />}<div className="grid gap-3 sm:grid-cols-3"><Summary label="Payment entries" value={payments.data.length} /><Summary label="Paid total" value={money(paid)} /><Summary label="Pending" value={payments.data.filter((row) => row.status === "PENDING").length} /></div><Card title="Payment register" action={<Select className="w-52" value={filter} onChange={(e) => setFilter(e.target.value)}><option value="">All vendors</option>{vendors.data.map((vendor) => <option key={vendor.id} value={vendor.id}>{vendor.companyName}</option>)}</Select>}><DataTable loading={payments.loading} rows={rows} columns={[{ header: "Payment", cell: (row) => <><p className="font-semibold">{row.paymentNumber}</p><p className="text-xs text-muted">{row.reference || "No reference"}</p></> }, { header: "Vendor", cell: (row) => row.vendorId?.companyName ?? "-" }, { header: "Period", cell: (row) => row.period || "-" }, { header: "Amount", cell: (row) => money(row.amount, row.currency) }, { header: "Status", cell: (row) => <Select className="h-8 min-w-32" value={row.status} onChange={(e) => update(row.id, e.target.value)}>{["PENDING", "PROCESSING", "PAID", "FAILED"].map((item) => <option key={item}>{item}</option>)}</Select> }, { header: "", sortable: false, cell: (row) => <Button className="h-8 !px-2" variant="danger" onClick={() => remove(row.id)}><Trash2 size={14} /></Button> }]} /></Card>{showForm && <Modal title="Add Vendor Payment" busy={busy} onClose={() => setShowForm(false)}><form className="grid gap-3" onSubmit={create}><Select required value={form.vendorId} onChange={(e) => setForm({ ...form, vendorId: e.target.value })}><option value="">Select vendor</option>{vendors.data.map((vendor) => <option key={vendor.id} value={vendor.id}>{vendor.companyName}</option>)}</Select><Input type="number" min="0.01" step="0.01" placeholder="Amount" required value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /><Input placeholder="Period, e.g. September 2026" value={form.period} onChange={(e) => setForm({ ...form, period: e.target.value })} /><Input placeholder="Transaction reference" value={form.reference} onChange={(e) => setForm({ ...form, reference: e.target.value })} /><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setShowForm(false)}>Cancel</Button><Button disabled={busy}>{busy ? "Saving..." : "Add Payment"}</Button></div></form></Modal>}</div>;
}

export function NotificationsPage() {
  const notifications = useApiResource("/api/notifications", []);
  const users = useApiResource("/api/users?pageSize=100", []);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ userId: "", type: "INFO", title: "", message: "" });
  const [error, setError] = useState("");
  async function create(event) { event.preventDefault(); try { await api("/api/notifications", { method: "POST", body: JSON.stringify(form) }); setShowForm(false); setForm({ userId: "", type: "INFO", title: "", message: "" }); await notifications.reload(); } catch (err) { setError(err.message); } }
  async function read(id) { await api(`/api/notifications/${id}/read`, { method: "PATCH" }); await notifications.reload(); }
  async function remove(id) { await api(`/api/notifications/${id}`, { method: "DELETE" }); await notifications.reload(); }
  return <div className="space-y-6"><PageHeader eyebrow="System" title="Notifications" action={<Button onClick={() => setShowForm(true)}><Plus size={16} />Notification</Button>} />{(notifications.error || error) && <ErrorState message={notifications.error || error} />}<div className="grid gap-3 sm:grid-cols-3"><Summary label="All notifications" value={notifications.data.length} /><Summary label="Unread" value={notifications.data.filter((row) => !row.readAt).length} /><Summary label="Read" value={notifications.data.filter((row) => row.readAt).length} /></div><Card title="Notification center">{!notifications.loading && !notifications.data.length ? <EmptyState title="No notifications" body="Create a notification for a user or the whole team." /> : <div className="divide-y divide-line">{notifications.data.map((row) => <article key={row.id} className={`flex gap-3 py-4 ${row.readAt ? "opacity-70" : ""}`}><span className="grid h-9 w-9 shrink-0 place-items-center rounded-md bg-teal-50 text-brand"><Bell size={17} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{row.title}</p><Badge tone={tone(row.type)}>{row.type}</Badge>{!row.readAt && <Badge tone="warning">Unread</Badge>}</div><p className="mt-1 text-sm text-muted">{row.message}</p><p className="mt-2 text-xs text-muted">{row.userId?.name ?? "All users"} · {date(row.createdAt)}</p></div><div className="flex gap-1">{!row.readAt && <Button className="h-8 !px-2" variant="secondary" onClick={() => read(row.id)} title="Mark read"><Check size={14} /></Button>}<Button className="h-8 !px-2" variant="danger" onClick={() => remove(row.id)} title="Delete"><Trash2 size={14} /></Button></div></article>)}</div>}</Card>{showForm && <Modal title="Create Notification" onClose={() => setShowForm(false)}><form className="grid gap-3" onSubmit={create}><Select value={form.userId} onChange={(e) => setForm({ ...form, userId: e.target.value })}><option value="">All users</option>{users.data.map((user) => <option key={user.id} value={user.id}>{user.name} ({user.email})</option>)}</Select><Select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}>{["INFO", "SUCCESS", "WARNING", "ERROR"].map((item) => <option key={item}>{item}</option>)}</Select><Input placeholder="Title" required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><Textarea placeholder="Message" required value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} /><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setShowForm(false)}>Cancel</Button><Button>Send</Button></div></form></Modal>}</div>;
}

export function SettingsPage() {
  const settings = useApiResource("/api/settings", {});
  const [form, setForm] = useState(null);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  useEffect(() => { if (settings.data?.id) setForm(settings.data); }, [settings.data]);
  if (!form) return <div className="space-y-6"><PageHeader eyebrow="System" title="Settings" />{settings.error && <ErrorState message={settings.error} onRetry={settings.reload} />}<Card><p className="text-sm text-muted">Loading settings...</p></Card></div>;
  async function save(event) { event.preventDefault(); setMessage(""); setError(""); try { const result = await api("/api/settings", { method: "PATCH", body: JSON.stringify(form) }); setForm(result); setMessage("Settings saved successfully."); } catch (err) { setError(err.message); } }
  return <div className="space-y-6"><PageHeader eyebrow="System" title="Settings" />{error && <ErrorState message={error} />}{message && <div className="rounded-md border border-emerald-200 bg-emerald-50 p-4 text-sm text-success">{message}</div>}<form className="grid gap-5 xl:grid-cols-2" onSubmit={save}><Card title="Organization"><div className="grid gap-4"><label className="grid gap-1.5 text-sm font-medium">Organization name<Input value={form.organizationName} onChange={(e) => setForm({ ...form, organizationName: e.target.value })} /></label><label className="grid gap-1.5 text-sm font-medium">Support email<Input type="email" value={form.supportEmail} onChange={(e) => setForm({ ...form, supportEmail: e.target.value })} /></label><label className="grid gap-1.5 text-sm font-medium">Default currency<Input maxLength={3} value={form.defaultCurrency} onChange={(e) => setForm({ ...form, defaultCurrency: e.target.value.toUpperCase() })} /></label></div></Card><Card title="Recording defaults"><div className="grid gap-4"><label className="grid gap-1.5 text-sm font-medium">Countdown seconds<Input type="number" min="0" max="30" value={form.recordingCountdown} onChange={(e) => setForm({ ...form, recordingCountdown: e.target.value })} /></label><label className="grid gap-1.5 text-sm font-medium">Default page size<Input type="number" min="10" max="200" value={form.defaultPageSize} onChange={(e) => setForm({ ...form, defaultPageSize: e.target.value })} /></label></div></Card><Card title="Workflow preferences" className="xl:col-span-2"><div className="grid gap-4 sm:grid-cols-2"><label className="flex items-center gap-3 rounded-md border border-line p-4"><input type="checkbox" checked={form.requireQaReview} onChange={(e) => setForm({ ...form, requireQaReview: e.target.checked })} /><span><span className="block text-sm font-semibold">Require QA review</span><span className="text-xs text-muted">Send uploaded recordings to the QA queue.</span></span></label><label className="flex items-center gap-3 rounded-md border border-line p-4"><input type="checkbox" checked={form.emailNotifications} onChange={(e) => setForm({ ...form, emailNotifications: e.target.checked })} /><span><span className="block text-sm font-semibold">Email notifications</span><span className="text-xs text-muted">Allow operational notification emails.</span></span></label></div><div className="mt-5 flex justify-end"><Button><Save size={16} />Save Settings</Button></div></Card></form></div>;
}
